apiVersion: v1
kind: Pod
metadata:
  name: test-quota
  labels:
    quota: enabled
  annotations:
    snapshots-quota: 100Mi
spec:
  containers:
  - name: test
    image: ubuntu:latest
    command: 
      - sleep
      - infinity
